# Licensed under the Apache-2.0 license

[package]
name = "hello-world-app"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
critical-section.workspace = true
embassy-executor.workspace = true
embassy-sync.workspace = true
libtock_console.workspace = true
libtock_debug_panic.workspace = true
libtock_platform.workspace = true
libtock_runtime.workspace = true
libtock.workspace = true
libtockasync.workspace = true
portable-atomic.workspace = true

# Change features to ["logger_b"] to use Logger B instead of Logger A
defmt-logger = { path = "../defmt-logger", features = ["logger_b"] }

[target.'cfg(not(target_arch = "riscv32"))'.dependencies]
libtock_unittest.workspace = true

[target.'cfg(target_arch = "riscv32")'.dependencies]
embassy-executor = { version = "0.6.3", features = ["arch-riscv32", "nightly"] }
embedded-alloc.workspace = true

[features]
default = []
debug = []
